### ISSUE TITLE
Does not work using Node 4

### ISSUE THREAD

**Issue by superkhau** [strongloop-internal/github-tools#15] opened 2015-10-21 23:01 UTC
Running `./bin/sync config.json` returns:

```
../github-tools/node_modules/github-cache/node_modules/level/node_modules/leveldown/node_modules/bindings/bindings.js:83
        throw e
        ^

Error: Module did not self-register.
    ...
```

**Comment by rmg** [comment] 2015-10-22 17:56
Pull requests welcome :-)

**Comment by cgole** [comment] 2015-10-28 20:38
Internal tool. Wont fix. Don't use with node-4 atm.

**Comment by rmg** [comment] 2015-10-29 04:36
@cgole if we don't use node-4, how will we know whether or not to recommend it to customers?

**Comment by rmg** [comment] 2015-10-29 04:37
@superkhau what version of leveldown was installed? v1.4.2 was released right around the time you reported this, but it's not clear when you actually installed the dependencies.

**Comment by superkhau** [comment] 2015-10-29 05:08
1.4.2

**Comment by rmg** [comment] 2015-10-29 05:24
@superkhau are you still able to reproduce this? It seems to be working fine for me..

**Comment by superkhau** [comment] 2015-10-29 05:39
Seems to work now after I deleted _cache.db and reran the command.

**Closed** 2015-10-29 05:39 UTC
Labels: bug

**Comment by superkhau** [comment] 2015-10-29 05:46
@rmg Is there a reason why we include _cache.db in the repo? Maybe we should just remove it since when you run `./bin/sync config.json`, it just gets regenerated anyways.

**Comment by rmg** [comment] 2015-10-29 05:56
I'm not sure why it is in the repo. I assume someone had a reason for it.

**Comment by superkhau** [comment] 2015-10-29 06:51
I think it's there by accident. We should add it to .gitignore. I'll submit a PR.
